version: '3.9'

services:
  job-agent:
    container_name: job-agent
    image: job-agent:latest
    restart: always
    env_file:
      - .env
    networks:
      - evolution_network

networks:
  evolution_network:
    external: true